service: itsligo-timetable-api

provider:
  name: aws
  runtime: python3.6
  region: eu-west-1
  stage: dev
  tags:
    project: timetable

package:
  include:
    - functions/timetable/**

functions:
  all:
    handler: functions/timetable/timetable.Handler
    events:
     - http:
         path: /timetable
         method: get
  class-count-today:
    handler: functions/counts/class-count-today.Handler
    events:
     - http:
         path: /class-count/today
         method: get
  classes-today:
    handler: functions/classes/classes-today.Handler
    events:
     - http:
         path: /classes/today
         method: get
  classes-tomorrow:
    handler: functions/classes/classes-tomorrow.Handler
    events:
     - http:
         path: /classes/tomorrow
         method: get
  next-class:
    handler: functions/classes/next-class.Handler
    events:
     - http:
         path: /classes/next
         method: get
  breaks-today:
    handler: functions/breaks/breaks-today.Handler
    events:
     - http:
         path: /breaks/today
         method: get
