service: itsligo-timetable-api

provider:
  name: aws
  runtime: python3.6
  region: eu-west-1
  stage: dev
  tags:
    project: timetable
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ses:SendEmail
        - ses:SendRawEmail
      Resource: "*"

package:
  include:
    - functions/timetable/**

functions:
  # Public API
  all:
    handler: public_api/timetable/timetable.Handler
    events:
     - http:
         path: /timetable
         method: get
         cors: true
     - http:
         path: /timetable
         method: post
         cors: true
  departments:
    handler: public_api/departments/departments.Handler
    events:
     - http:
         path: /departments
         method: get
         cors: true
  courses:
    handler: public_api/departments/courses.Handler
    events:
     - http:
         path: /courses
         method: get
         cors: true
  # Alexa API
  class-count-today:
    handler: alexa/counts/class_count_today.Handler
    events:
     - http:
         path: /class-count/today
         method: get
         cors: true
  classes-today:
    handler: alexa/classes/classes_today.Handler
    events:
     - http:
         path: /classes/today
         method: get
         cors: true
  classes-tomorrow:
    handler: alexa/classes/classes_tomorrow.Handler
    events:
     - http:
         path: /classes/tomorrow
         method: get
         cors: true
  next-class:
    handler: alexa/classes/next_class.Handler
    events:
     - http:
         path: /classes/next
         method: get
         cors: true
  breaks-today:
    handler: alexa/breaks/breaks_today.Handler
    events:
     - http:
         path: /breaks/today
         method: get
         cors: true
  # Private API
  auth:
    handler: private_api/users/authenticate_user.Handler
    events:
     - http:
         path: /auth
         method: post
         cors: true
  login:
    handler: private_api/users/login.Handler
    events:
     - http:
         path: /login
         method: post
         cors: true
  register:
    handler: private_api/users/register.Handler
    events:
     - http:
         path: /register
         method: post
         cors: true
  confirm:
    handler: private_api/users/confirm_email.Handler
    events:
     - http:
         path: /confirm
         method: post
         cors: true
  change_timetable:
    handler: private_api/users/change_timetable.Handler
    events:
     - http:
         path: /change-timetable
         method: post
         cors: true
